name: Run web
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # 赋予 GITHUB_TOKEN 推送权限 ✅

env:
  WEBNM: ${{ secrets.WEBNM || 'test79' }}
  UUID: ${{ secrets.UUID || 'de04add9-5b68-8bab-950c-08cd5320df18' }}
  VMESS: ${{ secrets.VMESS || 'vmess' }}
  VLESS: ${{ secrets.VLESS || 'vless' }}
  TROJAN: ${{ secrets.TROJAN || 'trojan' }}
  SHADOWSOCKS: ${{ secrets.SHADOWSOCKS || 'shadowsocks' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ 确保 checkout 是最新版本

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.5

      - name: Run xray
        run: |
          go version
          wget https://github.com/XTLS/Xray-core/archive/refs/tags/v1.7.2.zip
          unzip v1.7.2.zip
          mv web.sh Xray-core-1.7.2
          cd Xray-core-1.7.2
          bash web.sh
          go build -o ${WEBNM} -trimpath -ldflags "-s -w -buildid=" ./main
          mv ${WEBNM} ../${WEBNM}  # 移动编译好的文件到仓库根目录

      - name: Commit and Push compiled binary
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ${{ env.WEBNM }}  # 添加编译后的文件
          git commit -m "Add compiled binary: ${{ env.WEBNM }}" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ 确保 GITHUB_TOKEN 被正确传递
