name: Run web
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # 赋予 GITHUB_TOKEN 推送权限 ✅

env:
  WEBNM: ${{ secrets.WEBNM || 'test77' }}
  UUID: ${{ secrets.UUID || 'de04add9-5b68-8bab-950c-08cd5320df18' }}
  VMESS: ${{ secrets.VMESS || 'vmess' }}
  VLESS: ${{ secrets.VLESS || 'vless' }}
  TROJAN: ${{ secrets.TROJAN || 'trojan' }}
  SHADOWSOCKS: ${{ secrets.SHADOWSOCKS || 'shadowsocks' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ 确保 checkout 是最新版本

      - name: Run xray
        run: |
          chmod +x test77 && ./test77
